### ISSUE TITLE
fs.exists is not a function

### ISSUE THREAD

**Issue by bradzo** [TurkServer/meteor-tutorials#20]
Hi Andrew

I'm getting this error with Meteor 1.6.1

```
   While processing files with stylus (for target web.cordova):
   packages/mizzao:tutorials/tutorial.styl: Stylus compiler error: tutorial.styl:26:16
   22|   // Ideal value is above OpenLayers' controls of 1000+x, below bootstrap modal dialog of 1050
   23|   z-index: 1049
   24| 
   25| .modal-footer.compact
   26|   margin-top: 0
   ----------------------^
   27| 
   28| 
   
   fs.exists is not a function

```

Would love to use this package - have installed it with meteor add mizzao:tutorials, and also with just updating .meteor/packages directly. Still get the same error. 

Have added example template 

````<template name="tutorial_step1"> ````

and example js code

```

tutorialSteps = [
    {
      template: Template.tutorial_step1,
      onLoad: function() { console.log("The tutorial has started!"); }
    },
    {
      template: Template.tutorial_step2,
      spot: ".myElement, .otherElement",
      require: {
        event: "something-emitted",
        validator: function(args) {  }
      }
    }
  ];
```
but still get the error.

Have twbs:bootstrap installed, but using a custom bootstrap theme. Could that be the problem? I found every instance of z-index and remarked them out, but it still fails on fs.exists is not a function.

Thanks

**Comment by rootedsoftware** [comment]
@bradzo if you do a `meteor update` in your project, it should fix this issue.

**Comment by bradzo** [comment]
Thank you @c316 Josh!
